apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
  labels:
    name: mysql
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30306
  selector:
    app: mysql
